/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Connection status for JavaScript */
export const enum ConnectionStatus {
  Disconnected = 0,
  Connecting = 1,
  Connected = 2,
  Error = 3
}
/**
 * WebTransport client for Node.js.
 *
 * This class provides WebTransport connectivity using the same implementation
 * as the native Rust VM. It maintains a persistent connection with automatic
 * reconnection and heartbeat handling.
 */
export declare class WebTransportClient {
  /**
   * Create a new WebTransport client and start connecting.
   *
   * @param url - WebTransport server URL (e.g., "https://localhost:4433")
   * @param certHash - Optional certificate hash for self-signed certs (hex string)
   */
  constructor(url: string, certHash?: string | undefined | null)
  /** Check if connected to the relay server. */
  isConnected(): boolean
  /** Check if registered with the relay (IP assigned). */
  isRegistered(): boolean
  /** Get current connection status. */
  status(): ConnectionStatus
  /** Get the MAC address as a hex string. */
  macAddress(): string
  /** Get the MAC address as a byte array. */
  macBytes(): Array<number>
  /** Get the assigned IP address (if any) as a string. */
  assignedIp(): string | null
  /** Get the assigned IP address as bytes (if any). */
  assignedIpBytes(): Array<number> | null
  /** Get the number of connection attempts. */
  connectionAttempts(): number
  /**
   * Send an Ethernet frame to the relay.
   * Returns true if sent successfully, false if not connected.
   */
  send(data: Buffer): boolean
  /**
   * Receive an Ethernet frame from the relay (non-blocking).
   * Returns the frame data or undefined if no frame available.
   */
  recv(): Buffer | null
  /**
   * Receive all pending Ethernet frames (non-blocking).
   * Returns an array of frame buffers.
   */
  recvAll(): Array<Buffer>
  /** Shut down the connection and cleanup. */
  shutdown(): void
}

